### ISSUE TITLE
cannot import name wraps_py2 after yank installation via conda/github

### ISSUE THREAD

**Issue by sstolzenberg** [choderalab/yank#608]
Hi,

after installing yank via omnia on conda or via github, I receive an error message that openmoltools cannot import wraps_py2 (see below).

Thanks,
Sebastian

/////////////////////////////////
(yank) $ yank
Traceback (most recent call last):
  File "~/anaconda/envs/yank/bin/yank", line 11, in <module>
    load_entry_point('yank==0.14.1', 'console_scripts', 'yank')()
  File "~/anaconda/envs/yank/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "~/anaconda/envs/yank/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "~/anaconda/envs/yank/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "~/anaconda/envs/yank/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "~/anaconda/envs/yank/lib/python2.7/site-packages/yank/__init__.py", line 14, in <module>
    from . import utils
  File "~/anaconda/envs/yank/lib/python2.7/site-packages/yank/utils.py", line 25, in <module>
    from openmoltools.utils import wraps_py2, unwrap_py2  # Shortcuts for other modules
ImportError: cannot import name wraps_py2

**Comment by Lnaden** [comment]
Odd. What version/commit of `openmoltools` are you running?

**Comment by Lnaden** [comment]
`conda list openmoltools` if you installed from conda

**Comment by sstolzenberg** [comment]
Hi Levi,

thanks for the hint:
I have been using
openmoltools              0.7.4
which is automatically installed with "conda install yank".

However, when I manually install 
openmoltools              0.7.5.dev0
via git before
conda install yank
, it now correctly loads in the wraps_py2 module

Thanks,
Sebastian

**Comment by Lnaden** [comment]
Glad that installing it by hand works. But I still find it odd that the function did not import. The `wraps_py2` function was added back in 0.7.2 so I found it odd it would work in 0.7.4. The only thing  I can think of is an old `.pyc` file from an older version that it was loading instead. I can't replicate it myself so something like that must be it.

**Comment by sstolzenberg** [comment]
yes, I think there was a conflict with pip that I didn't see with conda, my bad
